# Generated by Django 2.0.7 on 2018-08-06 22:42

import ckeditor_uploader.fields
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', mdeditor.fields.MDTextField()),
                ('imgurl', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField()),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('prog', models.PositiveIntegerField(choices=[(0, '×'), {1, '√'}])),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('siteurl', models.CharField(blank=True, max_length=150)),
                ('timestamp', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
