# Generated by Django 2.0 on 2018-08-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180811_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='color',
            field=models.CharField(default='#242424', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='pos',
            field=models.CharField(default='200px|600px', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
